### ISSUE TITLE
Error detected while processing function <SNR>53_go:

### ISSUE THREAD

**Issue by twe4ked** [AaronLasseigne/yank-code#2]
```
Error detected while processing function <SNR>53_go:
line   13:
E15: Invalid expression: '';
```

Any ideas? Thanks!

**Comment by AaronLasseigne** [comment]
Yup, this is totally my bad. I pushed an update and accidentally had a `;`. I quickly force pushed a fix and hoped that no one got the bad one. Clearly that was a bad idea. If you delete the plugin and reinstall it'll be fixed. Sorry. :(

**Comment by twe4ked** [comment]
Thanks for the quick reply. It's working great now. 💯

**Comment by danbruegge** [comment]
@AaronLasseigne for me it still exists but only on `json` filetype.

**Comment by AaronLasseigne** [comment]
It looks like the JSON issue is different. I've opened a new ticket for it. #3
